### ISSUE TITLE
is this active?

### ISSUE THREAD

**Issue by argriffing** [scikit-learn/scikit-learn-benchmarks#2]
I am looking for ways that different projects do continuous performance regression testing.  I've heard that scikit-learn does this.  Is this the github project that is associated with scikit-learn's vbench'ing?

**Comment by ogrisel** [comment]
No this is no longer active. Another framework that looks nice for continuous benchmarks is Airspeed Velocity: http://spacetelescope.github.io/asv/using.html

**Comment by argriffing** [comment]
> No this is no longer active.

Is continuous benchmarking in scikit-learn still active, using a different project?

> Another framework that looks nice for continuous benchmarks is Airspeed Velocity

Does scikit-learn use this?

**Comment by ogrisel** [comment]
No continuous benchmarking is not active in scikit-learn. The existing vbench infra should be quite easy to reenable though. But airspeed velocity seems to be more full features.

**Comment by jeremiedbb** [comment]
This repo is being repurposed to host results of a new asv benchmark suite. I'm closing this.
